
spring:
  data:
    cassandra:
      keyspace-name: rechub
      username: IBWFZWylDFshXkPWkWynSHtQ
      password: bo7163XugL.h+F5Y,45iA.UPBbBmezXJOFcJjGRDnzdqmTQMlDBRY3bW-W7Zj-,3Ra1-RfLDZ2+6e656m84h5n13RqbZiO-xJqIg596yzZ3M5MBxruii+vaCePLqh,+s
      schema-action: recreate-drop-unused
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s

datastax.astra:
  secure-connect-bundle: connect.zip

astra:
  db:
    id: 60346226-2d87-4c50-975b-156c759cb766
    region: europe-west1
    keyspace: rechub
    application:
      token: AstraCS:IBWFZWylDFshXkPWkWynSHtQ:5ee46a0490ed5e158992c8f173346e5cfd52d2cc60d8e73dcd556c3ff906f337